#pragma once

#include <iostream>
#include <string>
#include <locale>
#include <codecvt>
#include <memory>
#include <algorithm>
#include <list>
#include <vector>
#include <unordered_map>
#include <queue>
#include <fstream>
#include <cmath>
#include <random>

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>

#include "json.hpp"
#include "rapidcsv.h"
#include "Defines.h"
#include "Enums.h"
#include "Types.h"
#include "Utils.h"
#include "Variables.h"
#include "ObjectPool.h"
#include "HitBox.h"
#include "HitBoxRect.h"
#include "HitBoxCircle.h"
#include "Game.h"
#include "FileManager.h"
#include "GameManager.h"
#include "InputManager.h"
#include "ResourceManager.h"
#include "SceneManager.h"
#include "SoundManager.h"
#include "GameObject.h"
#include "SpriteGameObject.h"
#include "TextGameObject.h"
#include "Scene.h"
#include "AnimationClip.h"
#include "Animator.h"